### PR TITLE
Accept searches with "IETF RFC XXXX"

### PR DESCRIPTION
**Pull request by ronaldtse**
Otherwise it only works with "RFC XXXX"

### CODE REVIEW

**Comment by opoudjis** [comment]
I can accept these, but they're actually beside the point: all rfcbib references are meant to be wrapped as `IETF(RFC nnnn)`, and this ends up licensing `IETF(IETF RFC nnnn)`, which noone will write. I'll change relaton as well, so it allows both `prefix(x)`, and `prefix x`.

**Comment by opoudjis** [comment]
Actually, no. If I strip `IETF` from `IETF RFC nnnn` in relaton, I have to strip `ISO` from `ISO 639`, and `ISO TR 5`, which is lunacy. The syntax is like it is for a reason: it is unambiguous. 

Relaton converts `IETF(RFC nnn)` to `RFC nnnn`, but it leaves `IETF RFC nnn` alone, because it leaves `ISO 639` alone: prefixes are not stripped if they are space delimited rather than bracket wrapped. So the code is now fine as is.

**Comment by ronaldtse** [comment]
The reason I made the patch is that the RFCBib gem crashes when I gave it “IETF RFC XXXX”. The change in search syntax affects all Metanorma document; we ought not to crash if Relaton doesn’t understand the search syntax, and it really should be more or less backwards compatible with the old syntax. 

People are actually using Metanorma (and hence the Relaton search syntax, which is a new thing), we can’t expect everyone to know how to convert the references and doing it manually. I didn’t even know this is related — the document was doing fine until I ran bundle update!

**Comment by ronaldtse** [comment]
In addition, we should be parsing the “XXXX” part of “RFC XXXX”, make sense of it first, before we fetch the URL. And any failure in fetching should not crash the gem. Yesterday it had an URL with a space in it and the HTTP class raised an error, which RFCBib did not catch and it crashed the whole chain.

**Comment by opoudjis** [comment]
And I did add the warning if the URL was not recognised if the document was neither I-D nor RFC. It's not robust code :-(

This sounds like I should detect whether the URL exists before fetching it and processing it. I'm making a ticket; please add to it the issues you're seeing.

**Pull request merged**
